#!/bin/bash
#jq can be found on https://github.com/jqlang/jq
ip=$(curl -s wtfismyip.com/text)
loc=$(curl -s https://ipapi.co/"$ip"/json/)
lat=$(echo "$loc" | jq -r '.latitude')
long=$(echo "$loc" | jq -r '.longitude')
city=$(echo "$loc" | jq -r '.city')
region=$(echo "$loc" | jq -r '.region_code')
country=$(echo "$loc" | jq -r '.country')
ver="0.1.3"
help(){
    echo "Weermeter $ver"
    echo "usage:"
    echo "-c (displays temperature in celcius)"
    echo "-d (displays meteo variable, debug)"
    echo "-f (displays temperature in fahrenheit)"
    echo "-h (displays this help prompt)"
    echo "-v (displays version)"
}
americatemp(){
    meteo=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=$lat&longitude=$long&current=temperature_2m,apparent_temperature,wind_speed_10m&wind_speed_unit=mph&temperature_unit=fahrenheit")
}
worldtemp(){
    meteo=$(curl -s "https://api.open-meteo.com/v1/forecast?latitude=$lat&longitude=$long&current=temperature_2m,apparent_temperature,wind_speed_10m")
}
if [[ "$1" = -h ]]; then
    help
    exit 0
fi
if [[ "$1" = -d ]]; then
    worldtemp
    echo "$meteo"
    echo "$loc"
    echo "$ip"
    exit 0
fi
if [[ "$1" = -v ]]; then
    echo "$ver"
    exit 0
fi
if [[ $country = 'US' || "$1" = -f ]]; then
    americatemp
fi
if [[ ! $country = 'US' || "$1" = -c ]]; then
    worldtemp
fi
current_temp=$(echo "$meteo" | jq -r -c '.current.temperature_2m')
tempunit=$(echo "$meteo" | jq -r -c '.current_units.temperature_2m')
feelslike=$(echo "$meteo" | jq -r -c '.current.apparent_temperature')
windspeed=$(echo "$meteo" | jq -r -c '.current.wind_speed_10m')
speedunit=$(echo "$meteo" | jq -r -c '.current_units.wind_speed_10m')
echo "$city, $region, $country"
echo "Coordinates: $lat, $long"
echo "Current temp: $current_temp $tempunit"
echo "Feels like: $feelslike $tempunit"
echo "Wind Speed: $windspeed $speedunit"